### ISSUE TITLE
Meminfo reports incorrect memory data

### ISSUE THREAD

**Issue by KungPaoChicken** [KungPaoChicken/android-runner#2]
Issue:
`meminfo` reports incorrect memory data when the device has more than 1GB RAM.

Status:
I need a meminfo result from a device that doesn't work.

Reference materials: 
https://developer.android.com/studio/command-line/dumpsys.html#meminfo
https://stackoverflow.com/questions/26776134/adb-shell-dumpsys-meminfo-what-is-the-meaning-of-each-cell-of-its-output

**Comment by 6366295** [comment]
Using the original code:
![meminfo_1](https://user-images.githubusercontent.com/1162273/33856990-37f60256-deca-11e7-900b-707892ad6308.png)

Using the remove all ',' and strip()[0:-1] code:
![meminfo_2](https://user-images.githubusercontent.com/1162273/33856991-3811eb38-deca-11e7-944f-baee990b1924.png)
